'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.20506.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("HostBot.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Client.
        '''</summary>
        Friend ReadOnly Property Command_Bot_Client() As String
            Get
                Return ResourceManager.GetString("Command_Bot_Client", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to root=3.
        '''</summary>
        Friend ReadOnly Property Command_Bot_Client_Access() As String
            Get
                Return ResourceManager.GetString("Command_Bot_Client_Access", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property Command_Bot_Client_ExtraHelp() As String
            Get
                Return ResourceManager.GetString("Command_Bot_Client_ExtraHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--client name command, --client main getport] Forwards commands to the named battlenet client run by the bot..
        '''</summary>
        Friend ReadOnly Property Command_Bot_Client_Help() As String
            Get
                Return ResourceManager.GetString("Command_Bot_Client_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connect.
        '''</summary>
        Friend ReadOnly Property Command_Bot_Connect() As String
            Get
                Return ResourceManager.GetString("Command_Bot_Connect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to root=4.
        '''</summary>
        Friend ReadOnly Property Command_Bot_Connect_Access() As String
            Get
                Return ResourceManager.GetString("Command_Bot_Connect_Access", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property Command_Bot_Connect_ExtraHelp() As String
            Get
                Return ResourceManager.GetString("Command_Bot_Connect_ExtraHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--Connect profile] Creates a client and logs it into a battle.net server..
        '''</summary>
        Friend ReadOnly Property Command_Bot_Connect_Help() As String
            Get
                Return ResourceManager.GetString("Command_Bot_Connect_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CreateAdmin.
        '''</summary>
        Friend ReadOnly Property Command_Bot_CreateAdmin() As String
            Get
                Return ResourceManager.GetString("Command_Bot_CreateAdmin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to root=5;games=5;users=5.
        '''</summary>
        Friend ReadOnly Property Command_Bot_CreateAdmin_Access() As String
            Get
                Return ResourceManager.GetString("Command_Bot_CreateAdmin_Access", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property Command_Bot_CreateAdmin_ExtraHelp() As String
            Get
                Return ResourceManager.GetString("Command_Bot_CreateAdmin_ExtraHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--CreateAdmin name password server_port receiver=localhost] Creates a server with an admin game and a LAN advertiser for the server..
        '''</summary>
        Friend ReadOnly Property Command_Bot_CreateAdmin_Help() As String
            Get
                Return ResourceManager.GetString("Command_Bot_CreateAdmin_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CreateCKL.
        '''</summary>
        Friend ReadOnly Property Command_Bot_CreateCKL() As String
            Get
                Return ResourceManager.GetString("Command_Bot_CreateCKL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--CreateCKL name listen_port=pooled] Starts a CD Key Lending server that others can connect to and use to logon to bnet. This will NOT allow others to learn your cd keys, but WILL allow them to logon with your keys ONCE..
        '''</summary>
        Friend ReadOnly Property Command_Bot_CreateCKL_Help() As String
            Get
                Return ResourceManager.GetString("Command_Bot_CreateCKL_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CreateClient.
        '''</summary>
        Friend ReadOnly Property Command_Bot_CreateClient() As String
            Get
                Return ResourceManager.GetString("Command_Bot_CreateClient", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--CreateClient name=generated] Creates a new battle.net client instance..
        '''</summary>
        Friend ReadOnly Property Command_Bot_CreateClient_Help() As String
            Get
                Return ResourceManager.GetString("Command_Bot_CreateClient_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CreateLan.
        '''</summary>
        Friend ReadOnly Property Command_Bot_CreateLan() As String
            Get
                Return ResourceManager.GetString("Command_Bot_CreateLan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to root=5.
        '''</summary>
        Friend ReadOnly Property Command_Bot_CreateLan_Access() As String
            Get
                Return ResourceManager.GetString("Command_Bot_CreateLan_Access", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property Command_Bot_CreateLan_ExtraHelp() As String
            Get
                Return ResourceManager.GetString("Command_Bot_CreateLan_ExtraHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [CreateLan name server_port receiver=localhost] Creates a lan advertiser..
        '''</summary>
        Friend ReadOnly Property Command_Bot_CreateLan_Help() As String
            Get
                Return ResourceManager.GetString("Command_Bot_CreateLan_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CreateServer.
        '''</summary>
        Friend ReadOnly Property Command_Bot_CreateServer() As String
            Get
                Return ResourceManager.GetString("Command_Bot_CreateServer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to root=4.
        '''</summary>
        Friend ReadOnly Property Command_Bot_CreateServer_Access() As String
            Get
                Return ResourceManager.GetString("Command_Bot_CreateServer_Access", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Options=[*]
        '''Admin=-Admin=Strilanc,-a=user,-a: Sets the auto-elevated username. Use no argument to match your name.
        '''Autostart=-Autostart, -as: Instances will start automatically when they fill up.
        '''Instances=-Instances=X, -i=X: Sets the initial number of instances. Use =0 for unlimited instances.
        '''FullShare=-FullShare: Turns on wc3&apos;s &apos;full shared control&apos; option.
        '''MultiObs=-MultiObs,-mo: Turns on observers, and creates a special slot which can accept large amounts of players. The map must have two availabl [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Command_Bot_CreateServer_ExtraHelp() As String
            Get
                Return ResourceManager.GetString("Command_Bot_CreateServer_ExtraHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--CreateServer name map -options] Creates a new wc3 game server. Use help --CreateSever Options for help with options..
        '''</summary>
        Friend ReadOnly Property Command_Bot_CreateServer_Help() As String
            Get
                Return ResourceManager.GetString("Command_Bot_CreateServer_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DownloadEpicWarMap.
        '''</summary>
        Friend ReadOnly Property Command_Bot_DownloadEpicWarMap() As String
            Get
                Return ResourceManager.GetString("Command_Bot_DownloadEpicWarMap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--DownloadEpicWarMap epic_war_map_number] Downloads a map from epicwar..
        '''</summary>
        Friend ReadOnly Property Command_Bot_DownloadEpicWarMap_Help() As String
            Get
                Return ResourceManager.GetString("Command_Bot_DownloadEpicWarMap_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FindMaps.
        '''</summary>
        Friend ReadOnly Property Command_Bot_FindMaps() As String
            Get
                Return ResourceManager.GetString("Command_Bot_FindMaps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--FindMaps map_query] Returns the first five maps matching the query..
        '''</summary>
        Friend ReadOnly Property Command_Bot_FindMaps_Help() As String
            Get
                Return ResourceManager.GetString("Command_Bot_FindMaps_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GetSetting.
        '''</summary>
        Friend ReadOnly Property Command_Bot_GetSetting() As String
            Get
                Return ResourceManager.GetString("Command_Bot_GetSetting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--GetSetting setting] Returns the value of a global setting. Supported settings are tickperiod, laglimit, commandprefix..
        '''</summary>
        Friend ReadOnly Property Command_Bot_GetSetting_Help() As String
            Get
                Return ResourceManager.GetString("Command_Bot_GetSetting_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to KillCKL.
        '''</summary>
        Friend ReadOnly Property Command_Bot_KillCKL() As String
            Get
                Return ResourceManager.GetString("Command_Bot_KillCKL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--KillCKL name] Kills a CD Key Lending server..
        '''</summary>
        Friend ReadOnly Property Command_Bot_KillCKL_Help() As String
            Get
                Return ResourceManager.GetString("Command_Bot_KillCKL_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to KillClient.
        '''</summary>
        Friend ReadOnly Property Command_Bot_KillClient() As String
            Get
                Return ResourceManager.GetString("Command_Bot_KillClient", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--KillClient name] Kills the named battle.net client instance..
        '''</summary>
        Friend ReadOnly Property Command_Bot_KillClient_Help() As String
            Get
                Return ResourceManager.GetString("Command_Bot_KillClient_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to KillLan.
        '''</summary>
        Friend ReadOnly Property Command_Bot_KillLan() As String
            Get
                Return ResourceManager.GetString("Command_Bot_KillLan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to root=5.
        '''</summary>
        Friend ReadOnly Property Command_Bot_KillLan_Access() As String
            Get
                Return ResourceManager.GetString("Command_Bot_KillLan_Access", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property Command_Bot_KillLan_ExtraHelp() As String
            Get
                Return ResourceManager.GetString("Command_Bot_KillLan_ExtraHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [KillLan name] Removes a lan advertiser..
        '''</summary>
        Friend ReadOnly Property Command_Bot_KillLan_Help() As String
            Get
                Return ResourceManager.GetString("Command_Bot_KillLan_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to KillServer.
        '''</summary>
        Friend ReadOnly Property Command_Bot_KillServer() As String
            Get
                Return ResourceManager.GetString("Command_Bot_KillServer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--KillServer name] Kills the named warcraft 3 game server instance..
        '''</summary>
        Friend ReadOnly Property Command_Bot_KillServer_Help() As String
            Get
                Return ResourceManager.GetString("Command_Bot_KillServer_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LoadPlugin.
        '''</summary>
        Friend ReadOnly Property Command_Bot_LoadPlugin() As String
            Get
                Return ResourceManager.GetString("Command_Bot_LoadPlugin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--loadplugin name] Loads a plugin..
        '''</summary>
        Friend ReadOnly Property Command_Bot_LoadPlugin_Help() As String
            Get
                Return ResourceManager.GetString("Command_Bot_LoadPlugin_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Server.
        '''</summary>
        Friend ReadOnly Property Command_Bot_Server() As String
            Get
                Return ResourceManager.GetString("Command_Bot_Server", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--server name command, --server main stoplistening] Forwards commands to the named warcraft 3 game server run by the bot..
        '''</summary>
        Friend ReadOnly Property Command_Bot_Server_Help() As String
            Get
                Return ResourceManager.GetString("Command_Bot_Server_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SetSetting.
        '''</summary>
        Friend ReadOnly Property Command_Bot_SetSetting() As String
            Get
                Return ResourceManager.GetString("Command_Bot_SetSetting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--SetSetting setting value] Sets a global setting. Supported settings are tickperiod, laglimit, commandprefix..
        '''</summary>
        Friend ReadOnly Property Command_Bot_SetSetting_Help() As String
            Get
                Return ResourceManager.GetString("Command_Bot_SetSetting_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AddUser.
        '''</summary>
        Friend ReadOnly Property Command_Client_AddUser() As String
            Get
                Return ResourceManager.GetString("Command_Client_AddUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to users=2.
        '''</summary>
        Friend ReadOnly Property Command_Client_AddUser_Access() As String
            Get
                Return ResourceManager.GetString("Command_Client_AddUser_Access", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property Command_Client_AddUser_ExtraHelp() As String
            Get
                Return ResourceManager.GetString("Command_Client_AddUser_ExtraHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--AddUser name] Adds a new user with the default new user permissions..
        '''</summary>
        Friend ReadOnly Property Command_Client_AddUser_Help() As String
            Get
                Return ResourceManager.GetString("Command_Client_AddUser_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AdLink.
        '''</summary>
        Friend ReadOnly Property Command_Client_AdLink() As String
            Get
                Return ResourceManager.GetString("Command_Client_AdLink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to root=3.
        '''</summary>
        Friend ReadOnly Property Command_Client_AdLink_Access() As String
            Get
                Return ResourceManager.GetString("Command_Client_AdLink_Access", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property Command_Client_AdLink_ExtraHelp() As String
            Get
                Return ResourceManager.GetString("Command_Client_AdLink_ExtraHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--AdLink other_client_name] Causes the other client to advertise the same games as this client. Note: If either client fails to advertise, they both fail..
        '''</summary>
        Friend ReadOnly Property Command_Client_AdLink_Help() As String
            Get
                Return ResourceManager.GetString("Command_Client_AdLink_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AdUnlink.
        '''</summary>
        Friend ReadOnly Property Command_Client_AdUnlink() As String
            Get
                Return ResourceManager.GetString("Command_Client_AdUnlink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to root=3.
        '''</summary>
        Friend ReadOnly Property Command_Client_AdUnlink_Access() As String
            Get
                Return ResourceManager.GetString("Command_Client_AdUnlink_Access", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property Command_Client_AdUnlink_ExtraHelp() As String
            Get
                Return ResourceManager.GetString("Command_Client_AdUnlink_ExtraHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [AdUnlink other_client_name] Causes the other client to no longer advertise the same games as this client..
        '''</summary>
        Friend ReadOnly Property Command_Client_AdUnlink_Help() As String
            Get
                Return ResourceManager.GetString("Command_Client_AdUnlink_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connect.
        '''</summary>
        Friend ReadOnly Property Command_Client_Connect() As String
            Get
                Return ResourceManager.GetString("Command_Client_Connect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to root=4.
        '''</summary>
        Friend ReadOnly Property Command_Client_Connect_Access() As String
            Get
                Return ResourceManager.GetString("Command_Client_Connect_Access", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property Command_Client_Connect_ExtraHelp() As String
            Get
                Return ResourceManager.GetString("Command_Client_Connect_ExtraHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Connect Hostname] Connects to a battle.net server at the given address..
        '''</summary>
        Friend ReadOnly Property Command_Client_Connect_Help() As String
            Get
                Return ResourceManager.GetString("Command_Client_Connect_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Elevate.
        '''</summary>
        Friend ReadOnly Property Command_Client_Elevate() As String
            Get
                Return ResourceManager.GetString("Command_Client_Elevate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property Command_Client_Elevate_Access() As String
            Get
                Return ResourceManager.GetString("Command_Client_Elevate_Access", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property Command_Client_Elevate_ExtraHelp() As String
            Get
                Return ResourceManager.GetString("Command_Client_Elevate_ExtraHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Elevate, Elevate username] Elevates you or a specified user to admin in your hosted game..
        '''</summary>
        Friend ReadOnly Property Command_Client_Elevate_Help() As String
            Get
                Return ResourceManager.GetString("Command_Client_Elevate_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GetPort.
        '''</summary>
        Friend ReadOnly Property Command_Client_GetPort() As String
            Get
                Return ResourceManager.GetString("Command_Client_GetPort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to root=1.
        '''</summary>
        Friend ReadOnly Property Command_Client_GetPort_Access() As String
            Get
                Return ResourceManager.GetString("Command_Client_GetPort_Access", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property Command_Client_GetPort_ExtraHelp() As String
            Get
                Return ResourceManager.GetString("Command_Client_GetPort_ExtraHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [GetPort] Returns the listen port reported to bnet..
        '''</summary>
        Friend ReadOnly Property Command_Client_GetPort_Help() As String
            Get
                Return ResourceManager.GetString("Command_Client_GetPort_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Host.
        '''</summary>
        Friend ReadOnly Property Command_Client_Host() As String
            Get
                Return ResourceManager.GetString("Command_Client_Host", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to games=1.
        '''</summary>
        Friend ReadOnly Property Command_Client_Host_Access() As String
            Get
                Return ResourceManager.GetString("Command_Client_Host_Access", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Options=[*]
        '''Admin=-Admin=Strilanc,-a=user,-a: Sets the auto-elevated username. Use no argument to match your name.
        '''Autostart=-Autostart, -as: Instances will start automatically when they fill up.
        '''Instances=-Instances=X, -i=X: Sets the initial number of instances. Use =0 for unlimited instances.
        '''FullShare=-FullShare: Turns on wc3&apos;s &apos;full shared control&apos; option.
        '''Grab=-Grab: Downloads the map file from joining players.
        '''LoadInGame=-LoadInGame, -lig: Players wait for loaders in the game. Nicer than staring [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Command_Client_Host_ExtraHelp() As String
            Get
                Return ResourceManager.GetString("Command_Client_Host_ExtraHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--Host gamename mapname -options] Creates a game server and advertises it. Mapname is matched to whatever -FindMaps returns. Use --Help Host Options for help with options..
        '''</summary>
        Friend ReadOnly Property Command_Client_Host_Help() As String
            Get
                Return ResourceManager.GetString("Command_Client_Host_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to login.
        '''</summary>
        Friend ReadOnly Property Command_Client_Login() As String
            Get
                Return ResourceManager.GetString("Command_Client_Login", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to root=4.
        '''</summary>
        Friend ReadOnly Property Command_Client_Login_Access() As String
            Get
                Return ResourceManager.GetString("Command_Client_Login_Access", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property Command_Client_Login_ExtraHelp() As String
            Get
                Return ResourceManager.GetString("Command_Client_Login_ExtraHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--login username password].
        '''</summary>
        Friend ReadOnly Property Command_Client_Login_Help() As String
            Get
                Return ResourceManager.GetString("Command_Client_Login_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RemoveUser.
        '''</summary>
        Friend ReadOnly Property Command_Client_RemoveUser() As String
            Get
                Return ResourceManager.GetString("Command_Client_RemoveUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to users=4.
        '''</summary>
        Friend ReadOnly Property Command_Client_RemoveUser_Access() As String
            Get
                Return ResourceManager.GetString("Command_Client_RemoveUser_Access", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property Command_Client_RemoveUser_ExtraHelp() As String
            Get
                Return ResourceManager.GetString("Command_Client_RemoveUser_ExtraHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [RemoveUser name] Removes an existing user..
        '''</summary>
        Friend ReadOnly Property Command_Client_RemoveUser_Help() As String
            Get
                Return ResourceManager.GetString("Command_Client_RemoveUser_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Say.
        '''</summary>
        Friend ReadOnly Property Command_Client_Say() As String
            Get
                Return ResourceManager.GetString("Command_Client_Say", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to root=1.
        '''</summary>
        Friend ReadOnly Property Command_Client_Say_Access() As String
            Get
                Return ResourceManager.GetString("Command_Client_Say_Access", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property Command_Client_Say_ExtraHelp() As String
            Get
                Return ResourceManager.GetString("Command_Client_Say_ExtraHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Say text] Makes the bot say stuff, including bnet commands..
        '''</summary>
        Friend ReadOnly Property Command_Client_Say_Help() As String
            Get
                Return ResourceManager.GetString("Command_Client_Say_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SetPort.
        '''</summary>
        Friend ReadOnly Property Command_Client_SetPort() As String
            Get
                Return ResourceManager.GetString("Command_Client_SetPort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to root=4.
        '''</summary>
        Friend ReadOnly Property Command_Client_SetPort_Access() As String
            Get
                Return ResourceManager.GetString("Command_Client_SetPort_Access", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property Command_Client_SetPort_ExtraHelp() As String
            Get
                Return ResourceManager.GetString("Command_Client_SetPort_ExtraHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [SetPort] Changes listen port reported to bnet..
        '''</summary>
        Friend ReadOnly Property Command_Client_SetPort_Help() As String
            Get
                Return ResourceManager.GetString("Command_Client_SetPort_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to StartAdvertising.
        '''</summary>
        Friend ReadOnly Property Command_Client_StartAdvertising() As String
            Get
                Return ResourceManager.GetString("Command_Client_StartAdvertising", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to root=4;games=5.
        '''</summary>
        Friend ReadOnly Property Command_Client_StartAdvertising_Access() As String
            Get
                Return ResourceManager.GetString("Command_Client_StartAdvertising_Access", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property Command_Client_StartAdvertising_ExtraHelp() As String
            Get
                Return ResourceManager.GetString("Command_Client_StartAdvertising_ExtraHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [StartAdvertising game_name map_query ...options] Adds an entry to the bnet games list. The only option is -private / -p..
        '''</summary>
        Friend ReadOnly Property Command_Client_StartAdvertising_Help() As String
            Get
                Return ResourceManager.GetString("Command_Client_StartAdvertising_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to StopAdvertising.
        '''</summary>
        Friend ReadOnly Property Command_Client_StopAdvertising() As String
            Get
                Return ResourceManager.GetString("Command_Client_StopAdvertising", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to root=4;games=5.
        '''</summary>
        Friend ReadOnly Property Command_Client_StopAdvertising_Access() As String
            Get
                Return ResourceManager.GetString("Command_Client_StopAdvertising_Access", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property Command_Client_StopAdvertising_ExtraHelp() As String
            Get
                Return ResourceManager.GetString("Command_Client_StopAdvertising_ExtraHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [StopAdvertising] Removes any entry in the bnet games list. Also unlinks any linked servers..
        '''</summary>
        Friend ReadOnly Property Command_Client_StopAdvertising_Help() As String
            Get
                Return ResourceManager.GetString("Command_Client_StopAdvertising_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Upload.
        '''</summary>
        Friend ReadOnly Property Command_Client_Upload() As String
            Get
                Return ResourceManager.GetString("Command_Client_Upload", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to games=2.
        '''</summary>
        Friend ReadOnly Property Command_Client_Upload_Access() As String
            Get
                Return ResourceManager.GetString("Command_Client_Upload_Access", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property Command_Client_Upload_ExtraHelp() As String
            Get
                Return ResourceManager.GetString("Command_Client_Upload_ExtraHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Upload game_name map_data].
        '''</summary>
        Friend ReadOnly Property Command_Client_Upload_Help() As String
            Get
                Return ResourceManager.GetString("Command_Client_Upload_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User.
        '''</summary>
        Friend ReadOnly Property Command_Client_User() As String
            Get
                Return ResourceManager.GetString("Command_Client_User", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property Command_Client_User_Access() As String
            Get
                Return ResourceManager.GetString("Command_Client_User_Access", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property Command_Client_User_ExtraHelp() As String
            Get
                Return ResourceManager.GetString("Command_Client_User_ExtraHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [User username=you] Shows a user&apos;s permissions..
        '''</summary>
        Friend ReadOnly Property Command_Client_User_Help() As String
            Get
                Return ResourceManager.GetString("Command_Client_User_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to help.
        '''</summary>
        Friend ReadOnly Property Command_General_Help() As String
            Get
                Return ResourceManager.GetString("Command_General_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--help, --help command_name] Displays a list of commands, or help for a specified command..
        '''</summary>
        Friend ReadOnly Property Command_General_Help_Help() As String
            Get
                Return ResourceManager.GetString("Command_General_Help_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Boot.
        '''</summary>
        Friend ReadOnly Property Command_Instance_Boot() As String
            Get
                Return ResourceManager.GetString("Command_Instance_Boot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--boot slot] Boots players in a slot from the game..
        '''</summary>
        Friend ReadOnly Property Command_Instance_Boot_Help() As String
            Get
                Return ResourceManager.GetString("Command_Instance_Boot_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bot.
        '''</summary>
        Friend ReadOnly Property Command_Instance_Bot() As String
            Get
                Return ResourceManager.GetString("Command_Instance_Bot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--Bot command] Forwards commands to the bot with full priviledges..
        '''</summary>
        Friend ReadOnly Property Command_Instance_Bot_Help() As String
            Get
                Return ResourceManager.GetString("Command_Instance_Bot_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend ReadOnly Property Command_Instance_Cancel() As String
            Get
                Return ResourceManager.GetString("Command_Instance_Cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--cancel] Closes the game server..
        '''</summary>
        Friend ReadOnly Property Command_Instance_Cancel_Help() As String
            Get
                Return ResourceManager.GetString("Command_Instance_Cancel_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close.
        '''</summary>
        Friend ReadOnly Property Command_Instance_Close() As String
            Get
                Return ResourceManager.GetString("Command_Instance_Close", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--close slot] Closes a slot, unless it contains a player..
        '''</summary>
        Friend ReadOnly Property Command_Instance_Close_Help() As String
            Get
                Return ResourceManager.GetString("Command_Instance_Close_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Disconnect.
        '''</summary>
        Friend ReadOnly Property Command_Instance_Disconnect() As String
            Get
                Return ResourceManager.GetString("Command_Instance_Disconnect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--disconnect] Causes the bot to disconnect from the game and attempt to pass hosting to one of the players..
        '''</summary>
        Friend ReadOnly Property Command_Instance_Disconnect_Help() As String
            Get
                Return ResourceManager.GetString("Command_Instance_Disconnect_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Elevate.
        '''</summary>
        Friend ReadOnly Property Command_Instance_Elevate() As String
            Get
                Return ResourceManager.GetString("Command_Instance_Elevate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Elevate password] Gives access to admin commands..
        '''</summary>
        Friend ReadOnly Property Command_Instance_Elevate_Help() As String
            Get
                Return ResourceManager.GetString("Command_Instance_Elevate_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Freeze.
        '''</summary>
        Friend ReadOnly Property Command_Instance_Freeze() As String
            Get
                Return ResourceManager.GetString("Command_Instance_Freeze", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--freeze slot, --freeze] Superlock. Stops players from modifying or leaving a slot or all slots..
        '''</summary>
        Friend ReadOnly Property Command_Instance_Freeze_Help() As String
            Get
                Return ResourceManager.GetString("Command_Instance_Freeze_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lock.
        '''</summary>
        Friend ReadOnly Property Command_Instance_Lock() As String
            Get
                Return ResourceManager.GetString("Command_Instance_Lock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--lock slot, --lock] Stops players from leaving a slot or all slots..
        '''</summary>
        Friend ReadOnly Property Command_Instance_Lock_Help() As String
            Get
                Return ResourceManager.GetString("Command_Instance_Lock_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open.
        '''</summary>
        Friend ReadOnly Property Command_Instance_Open() As String
            Get
                Return ResourceManager.GetString("Command_Instance_Open", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--open slot] Opens a slot, unless it contains a player..
        '''</summary>
        Friend ReadOnly Property Command_Instance_Open_Help() As String
            Get
                Return ResourceManager.GetString("Command_Instance_Open_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ping.
        '''</summary>
        Friend ReadOnly Property Command_Instance_Ping() As String
            Get
                Return ResourceManager.GetString("Command_Instance_Ping", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--ping] Displays estimated latency (Round-Trip-Time) for all players..
        '''</summary>
        Friend ReadOnly Property Command_Instance_Ping_Help() As String
            Get
                Return ResourceManager.GetString("Command_Instance_Ping_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reserve.
        '''</summary>
        Friend ReadOnly Property Command_Instance_Reserve() As String
            Get
                Return ResourceManager.GetString("Command_Instance_Reserve", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--reserve slot player_name] Reserves a slot for a player..
        '''</summary>
        Friend ReadOnly Property Command_Instance_Reserve_Help() As String
            Get
                Return ResourceManager.GetString("Command_Instance_Reserve_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SetColor.
        '''</summary>
        Friend ReadOnly Property Command_Instance_SetColor() As String
            Get
                Return ResourceManager.GetString("Command_Instance_SetColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--SetColor slot color] Sets a slot&apos;s color. Can&apos;t duplicate colors..
        '''</summary>
        Friend ReadOnly Property Command_Instance_SetColor_Help() As String
            Get
                Return ResourceManager.GetString("Command_Instance_SetColor_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SetComputer.
        '''</summary>
        Friend ReadOnly Property Command_Instance_SetComputer() As String
            Get
                Return ResourceManager.GetString("Command_Instance_SetComputer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--SetComputer slot difficulty] Places a computer in a slot, unless it contains a player..
        '''</summary>
        Friend ReadOnly Property Command_Instance_SetComputer_Help() As String
            Get
                Return ResourceManager.GetString("Command_Instance_SetComputer_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SetHandicap.
        '''</summary>
        Friend ReadOnly Property Command_Instance_SetHandicap() As String
            Get
                Return ResourceManager.GetString("Command_Instance_SetHandicap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--SetHandicap slot handicap] Sets a slot&apos;s handicap. Only allows 50,60,70,80,90,100..
        '''</summary>
        Friend ReadOnly Property Command_Instance_SetHandicap_Help() As String
            Get
                Return ResourceManager.GetString("Command_Instance_SetHandicap_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SetTeam.
        '''</summary>
        Friend ReadOnly Property Command_Instance_SetTeam() As String
            Get
                Return ResourceManager.GetString("Command_Instance_SetTeam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--SetTeam slot team] Sets a slot&apos;s team..
        '''</summary>
        Friend ReadOnly Property Command_Instance_SetTeam_Help() As String
            Get
                Return ResourceManager.GetString("Command_Instance_SetTeam_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SetTeams.
        '''</summary>
        Friend ReadOnly Property Command_Instance_SetTeams() As String
            Get
                Return ResourceManager.GetString("Command_Instance_SetTeams", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--SetTeams 3v3, --SetTeams 2v2v2] Opens and closes slots based on team sizes..
        '''</summary>
        Friend ReadOnly Property Command_Instance_SetTeams_Help() As String
            Get
                Return ResourceManager.GetString("Command_Instance_SetTeams_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start.
        '''</summary>
        Friend ReadOnly Property Command_Instance_Start() As String
            Get
                Return ResourceManager.GetString("Command_Instance_Start", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--start] Starts the launch countdown..
        '''</summary>
        Friend ReadOnly Property Command_Instance_Start_Help() As String
            Get
                Return ResourceManager.GetString("Command_Instance_Start_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Swap.
        '''</summary>
        Friend ReadOnly Property Command_Instance_Swap() As String
            Get
                Return ResourceManager.GetString("Command_Instance_Swap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--swap slot1 slot2] Swaps the contents of two slots..
        '''</summary>
        Friend ReadOnly Property Command_Instance_Swap_Help() As String
            Get
                Return ResourceManager.GetString("Command_Instance_Swap_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unlock.
        '''</summary>
        Friend ReadOnly Property Command_Instance_Unlock() As String
            Get
                Return ResourceManager.GetString("Command_Instance_Unlock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [--unlock slot, --unlock] Enables players to leave and modify a slot or all slots..
        '''</summary>
        Friend ReadOnly Property Command_Instance_Unlock_Help() As String
            Get
                Return ResourceManager.GetString("Command_Instance_Unlock_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VoteStart.
        '''</summary>
        Friend ReadOnly Property Command_Instance_VoteStart() As String
            Get
                Return ResourceManager.GetString("Command_Instance_VoteStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [VoteStart, VoteStart cancel] Votes to start the game. Only works in autostarted games. Requires at least 2 players and at least a 2/3 majority..
        '''</summary>
        Friend ReadOnly Property Command_Instance_VoteStart_Help() As String
            Get
                Return ResourceManager.GetString("Command_Instance_VoteStart_Help", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property HostBotIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("HostBotIcon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Instance &apos;{0}&apos; is already closed..
        '''</summary>
        Friend ReadOnly Property Instance_AlreadyClosed_f0name() As String
            Get
                Return ResourceManager.GetString("Instance_AlreadyClosed_f0name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Instance &apos;{0}&apos; closed..
        '''</summary>
        Friend ReadOnly Property Instance_Closed_f0name() As String
            Get
                Return ResourceManager.GetString("Instance_Closed_f0name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Instance &apos;{0}&apos; launched..
        '''</summary>
        Friend ReadOnly Property Instance_Launched_f0name() As String
            Get
                Return ResourceManager.GetString("Instance_Launched_f0name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HostBot.
        '''</summary>
        Friend ReadOnly Property ProgramName() As String
            Get
                Return ResourceManager.GetString("ProgramName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property ProgramShowoff_f0name() As String
            Get
                Return ResourceManager.GetString("ProgramShowoff_f0name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No slot matching &apos;{0}&apos;..
        '''</summary>
        Friend ReadOnly Property Slot_NotMatched_f0pattern() As String
            Get
                Return ResourceManager.GetString("Slot_NotMatched_f0pattern", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
