Imports System.Runtime.CompilerServices

Namespace Functional.Queueing
    '''<summary>Describes a thread-safe call queue for non-blocking calls.</summary>
    <ContractClass(GetType(ContractClassForICallQueue))>
    Public Interface ICallQueue
        '''<summary>Queues an action to be run and returns a future for the action's eventual completion.</summary>
        Function QueueAction(ByVal action As Action) As IFuture
    End Interface
    <ContractClassFor(GetType(ICallQueue))>
    Public Class ContractClassForICallQueue
        Implements ICallQueue
        Public Function QueueAction(ByVal action As Action) As Futures.IFuture Implements ICallQueue.QueueAction
            Contract.Requires(action IsNot Nothing)
            Contract.Ensures(Contract.Result(Of IFuture)() IsNot Nothing)
            Return Nothing
        End Function
    End Class

    Public Module ExtensionsForICallQueue
        '''<summary>Queues a function to be run and returns a future for the function's eventual output.</summary>
        <Extension()>
        Public Function QueueFunc(Of R)(ByVal queue As ICallQueue, ByVal func As Func(Of R)) As IFuture(Of R)
            Contract.Requires(queue IsNot Nothing)
            Contract.Requires(func IsNot Nothing)
            Contract.Ensures(Contract.Result(Of IFuture(Of R))() IsNot Nothing)
            Dim func_ = func
            Dim f As New Future(Of R)
            queue.QueueAction(Sub() f.SetValue(func_()))
            Return f
        End Function
    End Module

    ''' <summary>
    ''' A multiple-producer, single-consumer queue for running actions in order.
    ''' Logs unexpected exceptions from queued calls.
    ''' </summary>
    ''' <remarks>
    ''' The consumer is generated by the producers when items to consume exist and no consumer exists.
    ''' The queue should never end up non-empty and potentially permanently non-consumed.
    ''' </remarks>
    Public MustInherit Class BaseLockFreeCallQueue
        Inherits BaseLockFreeConsumer(Of Node)
        Implements ICallQueue
        Public Class Node
            Public ReadOnly action As Action
            Public ReadOnly future As New future
            Public Sub New(ByVal action As Action)
                Me.action = action
            End Sub
        End Class

        ''' <summary>
        ''' Queues an action to be run and returns a future for the action's eventual completion.
        ''' Starts running calls from the if they were not already being run.
        '''</summary>
        Public Function QueueAction(ByVal action As Action) As IFuture Implements ICallQueue.QueueAction
            Dim item = New Node(action)
            EnqueueConsume(item)
            Return item.future
        End Function

        '''<summary>Runs queued calls until there are none left.</summary>
        Protected Overrides Sub Consume(ByVal item As Node)
            If My.Settings.debugMode Then
                Call item.action()
            Else
                Try
                    Call item.action()
                Catch ex As Exception
                    Logging.LogUnexpectedException("Exception rose past {0}.Run()".frmt(Me.GetType.Name), ex)
                End Try
            End If
            Call item.future.SetReady()
        End Sub
    End Class

    '''<summary>Runs queued calls on a control's thread.</summary>
    Public Class InvokedCallQueue
        Inherits BaseLockFreeCallQueue
        Private ReadOnly control As Control
        Public Sub New(ByVal control As Control)
            Contract.Requires(control IsNot Nothing)
            Me.control = control
        End Sub
        Protected Overrides Sub StartRunning()
            Try
                control.BeginInvoke(Sub() Run())
            Catch e As InvalidOperationException
                Logging.LogUnexpectedException("Invalid Invoke from {0}.StartRunning() ({1}, {2})".frmt(Me.GetType.Name, control.GetType.Name, control.Name), e)
            End Try
        End Sub
    End Class

    '''<summary>Runs queued calls on an independent thread.</summary>
    Public Class ThreadedCallQueue
        Inherits BaseLockFreeCallQueue
        Private ReadOnly thread_name As String
        Public Sub New(Optional ByVal thread_name As String = Nothing)
            Me.thread_name = thread_name
        End Sub
        Protected Overrides Sub StartRunning()
            ThreadedAction(Sub() Run(), thread_name)
        End Sub
    End Class

    '''<summary>Runs queued calls on the thread pool.</summary>
    Public Class ThreadPooledCallQueue
        Inherits BaseLockFreeCallQueue
        Protected Overrides Sub StartRunning()
            ThreadPooledAction(Sub() Run())
        End Sub
    End Class
End Namespace
